# Generated by Django 4.0.4 on 2022-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consultas'], [1, 'Reclamos'], [2, 'Sugerencias']])),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
